### ISSUE TITLE
Google Analytic Download Event Tracking

### ISSUE THREAD

**Issue by naymin** [appserver-io/website#1]
Event Tracking for Download Page to know how many files have benn downloaded. Here is the code example that can be implemented on href link on the download page.
<a href="#" onClick="_gaq.push(['_trackEvent', 'Videos', 'Play', 'Baby\'s First Birthday']);">Play</a> nur so bauen
https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuideGoogle Analytic

**Comment by wick-ed** [comment]
This issue has been taken care of with the launch of our new site.
see http://appserver.io/downloads.html
