### ISSUE TITLE
Site Source in Version Control

### ISSUE THREAD

**Issue by Omeryl** [appserver-io/website#2]
Why don't you just put the site under GitHub version control? I'd love to just take a hammer against it to fix the typos I see on several pages and that would likely be a much more efficient method of doing so.

**Comment by willkommers** [comment]
The page is already on github. Just go to the repository https://github.com/appserver-io/appserver and change the branch to gh-pages. Feel free to fix typos and verbalizations we really appreciate your help. If there is anything else I can help you with just let me know.

**Comment by Omeryl** [comment]
Whoops, my bad. You should add something to this repo's README ;).

**Comment by wick-ed** [comment]
Done with [this commit](https://github.com/appserver-io/website/commit/e319cca272238b8eebcbe246cf8b291f6844d8cd)
